apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
    example: simple_pod
spec:
  containers:
  - name: myapp
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

## This is a simple menifest file for creating a K8 pod, that runs a redis container
## Run the below command
## kubectl apply -f <path-to-this-menifest-file> : This will create a pod
## kubectl get pods : This will list the pods in the default namespace
## kubectl get pods/myapp -o wide : This will give more details of the pod myapp
## kubectl describe pods/myapp : This will give all details of the pos myapp

